name: Rust

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/**"

  pull_request:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  combined:
    runs-on: depot-ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: backend
          cache-on-failure: true

      - name: Install latest rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Run checks
        working-directory: backend
        run: |
          set -e
          cargo check --no-default-features || { echo "cargo check failed"; CHECK_FAILED=1; }
          cargo clippy -- -D warnings || { echo "cargo clippy failed"; CLIPPY_FAILED=1; }
          cargo fmt -- --check || { echo "cargo fmt failed"; FMT_FAILED=1; }
          if [ "$CHECK_FAILED" -o "$CLIPPY_FAILED" -o "$FMT_FAILED" ]; then
            echo "One or more checks failed."
            exit 1
          fi
