name: "ts-tests"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ts-tests:
    name: TypeScript Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install Dependencies
        run: pnpm install
      - name: TypeScript Tests
        run: pnpm test-once
