name: "tsc-check"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tsc-check:
    name: TypeScript Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.TS_CLONE_DEPLOY_KEY }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install Dependencies
        run: pnpm install
      - name: Check Tauri Plugin Versions
        run: node script/check-tauri-versions
      - name: TypeScript Check
        run: ./node_modules/.bin/tsc --noEmit
